return action_shoot_create([
	/*color*/ my_shoot_color,
	/*bullet_type*/ my_shoot_bullet_type,
	/*bullet_speed*/ my_shoot_bullet_speed,
	/*bullet_range*/ my_shoot_bullet_range,
	/*bullet_radius*/ my_shoot_bullet_radius,
	/*bullet_count*/ my_shoot_bullet_count,
	/*bullet_particles*/ my_shoot_bullet_particles,
	/*bullet_impact_health*/ my_shoot_bullet_impact_health,
	/*bullet_explosion_radius*/ my_shoot_bullet_explosion_radius,
	/*bullet_explosion_trigger*/ my_shoot_bullet_explosion_trigger,	
	/*bullet_chaos_speed*/ my_shoot_bullet_chaos_speed,
	/*bullet_chaos_range*/ my_shoot_bullet_chaos_range,
	/*bullet_chaos_angle*/ my_shoot_bullet_chaos_angle,
	/*bullet_angle_spread*/ my_shoot_bullet_angle_spread,
	/*bullet_seek_range*/ my_shoot_bullet_seek_turn_rate,
	/*bullet_seek_turn_rate*/ my_shoot_bullet_seek_turn_rate,
	/*bullet_seek_angle_limit*/ 180,
	/*bullet_seek_no_decay*/ false,
	/*bullet_tile_phase*/ action_shoot_bullet_tile_phase,
	/*damage*/ my_shoot_damage,
	/*flinch*/ my_shoot_flinch,
	/*push*/ my_shoot_push,
	
	/*fire_recoil*/ my_shoot_fire_recoil,
	/*combo_max*/ my_shoot_combo_max,
	
	/*cast_value*/ my_shoot_cast_value,
	/*channel_value*/ my_shoot_channel_value,
	/*backswing_value*/ my_shoot_backswing_value,
	/*cooldown_value*/ my_shoot_cooldown_value	
]);